/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScentFinderRouteImport } from './routes/scent-finder'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivateLabelRouteImport } from './routes/private-label'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ScentFinderRoute = ScentFinderRouteImport.update({
  id: '/scent-finder',
  path: '/scent-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLabelRoute = PrivateLabelRouteImport.update({
  id: '/private-label',
  path: '/private-label',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/manufacturing': typeof ManufacturingRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/scent-finder': typeof ScentFinderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/manufacturing': typeof ManufacturingRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/scent-finder': typeof ScentFinderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/brands': typeof BrandsRoute
  '/contact': typeof ContactRoute
  '/manufacturing': typeof ManufacturingRoute
  '/private-label': typeof PrivateLabelRoute
  '/products': typeof ProductsRoute
  '/scent-finder': typeof ScentFinderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/brands'
    | '/contact'
    | '/manufacturing'
    | '/private-label'
    | '/products'
    | '/scent-finder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/brands'
    | '/contact'
    | '/manufacturing'
    | '/private-label'
    | '/products'
    | '/scent-finder'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/brands'
    | '/contact'
    | '/manufacturing'
    | '/private-label'
    | '/products'
    | '/scent-finder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BrandsRoute: typeof BrandsRoute
  ContactRoute: typeof ContactRoute
  ManufacturingRoute: typeof ManufacturingRoute
  PrivateLabelRoute: typeof PrivateLabelRoute
  ProductsRoute: typeof ProductsRoute
  ScentFinderRoute: typeof ScentFinderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scent-finder': {
      id: '/scent-finder'
      path: '/scent-finder'
      fullPath: '/scent-finder'
      preLoaderRoute: typeof ScentFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/private-label': {
      id: '/private-label'
      path: '/private-label'
      fullPath: '/private-label'
      preLoaderRoute: typeof PrivateLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BrandsRoute: BrandsRoute,
  ContactRoute: ContactRoute,
  ManufacturingRoute: ManufacturingRoute,
  PrivateLabelRoute: PrivateLabelRoute,
  ProductsRoute: ProductsRoute,
  ScentFinderRoute: ScentFinderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
